# Generated by Django 5.1.7 on 2025-03-17 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeFinderApp', '0002_recipe_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('current_position', models.CharField(max_length=200)),
                ('establishment', models.CharField(blank=True, max_length=200, null=True)),
                ('certificate', models.FileField(upload_to='chef_certificates/')),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chef Verification',
                'verbose_name_plural': 'Chef Verifications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
