# Generated by Django 5.1.7 on 2025-03-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeFinderApp', '0003_chefverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='collection_images/'),
        ),
    ]
